version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend/app:/app/app
    environment:
      - ENVIRONMENT=dev
  frontend:
    environment:
      - ENVIRONMENT=dev
    volumes:
      - ./frontend/static:/usr/share/nginx/html
